PROJECT_NAME_MAX_LENGTH = 200
PROJECTS_PER_PAGE = 12
SKILL_NAME_MAX_LENGTH = 124
SKILL_SEARCH_LIMIT = 10

STATUS_OPEN = "open"
STATUS_CLOSED = "closed"

STATUS_CHOICES = (
    (STATUS_OPEN, "Open"),
    (STATUS_CLOSED, "Closed"),
)

STATUS_MAX_LENGTH = max(
    len(STATUS_OPEN),
    len(STATUS_CLOSED),
)
