# Generated by Django 5.2.4 on 2026-04-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name', 'surname'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
